# .properties ??? ???? ?? yml(??) ??? ???? ????.
# yml ??? ????? ???? ????? ????.

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: 1234
  jpa:
    database: mysql
#    mysql??? ????? InnoDB(??? ??)? ?? ?? ??
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    jpa ??? ?? ?? ???, ?? ? ????? ???? ??.
#    ??? ddl ??? ???, ??? ????? ?? ??
    generate-ddl: true
    hibernate:
#      create ??? ?? table? drop? create
#      update ??? ????? alter? ??
#      ?????  validate ???? ??? ?? ??? ???.
      ddl-auto: create
#    ?? show_sql: true ??? ?????? ????? query? console? ???? ?.
      show_sql: true



